### ISSUE TITLE
Create mock-up page about how the user interface should look

### ISSUE THREAD

**Issue by oscheller1** [oscheller1/hangman2017#2]

**Comment by sschorge** [comment]
I did a first Mock-Up for our GUI. Glad about Feedback and comments.
![main_page](https://user-images.githubusercontent.com/32512738/31454542-0f1dc312-aeb6-11e7-8735-1acd99433004.png)
![functions_page](https://user-images.githubusercontent.com/32512738/31454543-0f3a2458-aeb6-11e7-83a0-2c0954c3c477.png)
![initial_page](https://user-images.githubusercontent.com/32512738/31454544-0f558f22-aeb6-11e7-985b-e061839e2d3c.png)

**Comment by JaceBeleeren** [comment]
Some more mock ups

![samplegame](https://user-images.githubusercontent.com/27225635/31609140-427d0496-b273-11e7-94e9-65b7632e1430.PNG)
![login2](https://user-images.githubusercontent.com/27225635/31609145-44ff3d92-b273-11e7-99a5-3d0d46ab4fc2.PNG)
![chat](https://user-images.githubusercontent.com/27225635/31609148-4711de00-b273-11e7-889a-f6cb177f07dd.PNG)
![maincontentpossibilities](https://user-images.githubusercontent.com/27225635/31609151-48e1641c-b273-11e7-8466-8fb6e096fe4a.PNG)

**Comment by JaceBeleeren** [comment]
Main Content Possibility #2 
![mock2](https://user-images.githubusercontent.com/27225635/31715736-414207c8-b405-11e7-893c-36995ce56dc3.PNG)
