### ISSUE TITLE
Create database structure

### ISSUE THREAD

**Issue by oscheller1** [oscheller1/hangman2017#4]
Create structure how all the objects should look inside the MongoDB

**Comment by JonasBGerth** [comment]
- [ ] Collection: User
   - UserId
   - Name
   - Passwort
   - Options
- [ ]  Collection: Games
   - GameId
   - Users
       - UserId
       - Score
       - Tries
   - Game Time 
   - Date Time String
   - High Score

- [ ] Collection: Leaderboard View?

**Comment by bainstack** [comment]
**Datenbankanbindung:**

To connect using the mongo shell:
mongo ds040637.mlab.com:40637/hangman -u <dbuser> -p <dbpassword>

To connect using a driver via the standard MongoDB URI (what's this?):
mongodb://<dbuser>:<dbpassword>@ds040637.mlab.com:40637/hangman
